#
# macros
#
[macros.clone]
    prefix = ["git", "clone"]
[macros.install]
    prefix = ["sudo", "pacman", "-S", "--noconfirm"]
[macros.enable]
    prefix = ["sudo", "systemctl", "enable"]
[macros.aur]
    prefix = ["yaourt", "-S", "--noconfirm"]
#
# system
#
[tasks.fish]
    rejects = [["which", "fish"]]
    cmds = [["@install", "fish"], ["chsh", "-s", "/usr/bin/fish"]]
    links = [[".config/fish/config.fish"],
        [".config/fish/fishfile"]]
[tasks.libreoffice]
    cmds = [["@install", "libreoffice-fresh"]]
[tasks.vim]
   cmds = [["@install", "neovim"]]
   links = [[".config/nvim/init.vim"]]
[tasks.urxvt]
    cmds = [["@install", "rxvt-unicode"]]
[tasks.audio]
    cmds = [["@install", "pulseaudio", "alsa-utils", "pavucontrol"]]
    links = [[".config/pavucontrol.ini"]]
[tasks.zip]
    cmds = [["@install", "unzip"]]
[tasks.common]
    cmds = [["@install", "arandr", "gimp", "keepassx2", "xf86-input-synaptics", "rofi", "mps-youtube", "kdenlive", "gpicview", "cmus", "smplayer", "livestreamer", "krita", "xautolock", "feh", "pcmanfm", "task", "trash-cli"]]
    links = [[".Xresources"],
            [".gitconfig"],
            [".gitignore"]]
[tasks.qutebrowser]
    cmds = [["@install", "qutebrowser"]]
    links = [[".config/qutebrowser/qutebrowser.conf"],
        [".config/qutebrowser/keys.conf"]]
[tasks.redshift]
    cmds = [["@install", "redshift"]]
    #links = [[".config/redshift.conf"],
    #    [".config/redshift/hooks/brightness.sh"]]
[tasks.fonts]
    links = [[".local/share/fonts"]]
[tasks.userpackage]
    cmds = [["@aur", "slack-desktop"],
        ["@aur", "telegram-desktop"],
        ["@aur", "trackma-git"]]
[tasks.vlc]
    cmds = [["@install", "vlc"], ["/usr/lib/vlc/vlc-cache-gen", "-f", "/usr/lib/vlc/plugins"]]
[tasks.i3]
    cmds = [["@aur", "lemonbar-xft-git"],
        ["@aur", "i3blocks"]]
    links = [[".i3"],
        [".scripts"],
        [".i3blocks.conf"]]
[tasks.powerline]
    cmds = [["@install", "powerline"]]
[tasks.ranger]
    cmds = [["@install", "ranger"]]
    links = [[".config/ranger/rc.conf"],
        [".config/ranger/rifle.conf"],
        [".config/ranger/scope.sh"]]
[tasks.dunst]
    cmds = [["@install", "dunst"]]
    links = [[".config/dunst/dunstrc"]]
[tasks.morc_menu]
    cmds = [["@aur", "morc_menu"]]
    links = [[".config/morc_menu/morc_menu_v1.conf"]]
[tasks.compton]
    cmds = [["@install", "compton"]]
    links = [[".config/compton.conf"]]
[tasks.teiler]
    cmds = [["@aur", "teiler"]]
    links = [[".config/teiler/config"]]
[tasks.default]
    deps = ["common", "vim", "fish", "libreoffice", "fonts", "audio", "powerline", "i3", "userpackage", "redshift", "ranger", "dunst", "morc_menu", "compton", "teiler", "qutebrowser"]
