#
# macros
#
[macros.clone]
    deps = ["git"]
    prefix = ["git", "clone"]
[macros.install__arch]
    ## Use yaourt instead of pacman
    ##prefix = ["sudo", "pacman", "-S", "--noconfirm"]
    deps = ["yaourt"]
    prefix = ["yaourt", "-S", "--noconfirm"]
[macros.install__ubuntu]
    prefix = ["sudo", "apt-get", "install", "--force-yes"]
[macros.enable]
    prefix = ["sudo", "systemctl", "enable"]

## Tasks
[tasks.git]
    rejects = [["which", "git"]]
    links = [[".gitconfig"],
            [".gitignore"]]
[tasks.git__arch]
    # Install git using pacman
    cmds = [["sudo", "pacman", "-S", "--noconfirm", "git"]]
[tasks.yaourt]
    deps = ["git"]
    rejects = [["which", "yaourt"]]
    cmds = [["git", "clone", "https://aur.archlinux.org/package-query.git"],
            ["cd", "package-query"],
            ["makepkg", "-si"],
            ["cd", ".."],
            ["git", "clone", "https://aur.archlinux.org/yaourt.git"],
            ["makepkg", "-si"],
            ["cd", ".."]]
[tasks.fish]
    rejects = [["which", "fish"]]
    cmds = [["@install", "fish"], ["chsh", "-s", "/usr/bin/fish"]]
    links = [[".config/fish"]]
[tasks.vim]
   rejects = [["which", "nvim"]]
   cmds = [["@install", "neovim"],
   # Download vim-plug
           ["curl", "-fLo", "~/.local/share/nvim/site/autoload/plug.vim",
            "--create-dirs", "\\", "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"]]
   links = [[".config/nvim/init.vim"]]
[tasks.audio]
    cmds = [["@install", "pulseaudio", "alsa-utils", "pavucontrol"]]
    links = [[".config/pavucontrol.ini"]]
[tasks.common]
    cmds = [["@install", "unzip"]]
    links = [[".Xresources"]]
[tasks.desktop]
    cmds = [["@install", "gimp", "keepassx2", "xf86-input-synaptics", "rofi", "mps-youtube", "xautolock", "feh", "pcmanfm"]]
[tasks.browser]
    cmds = [["@install", "opera"]]
[tasks.redshift]
    cmds = [["@install", "redshift"]]
[tasks.mpv]
    cmds = [["@install", "mpv"]]
    links = [[".config/mpv/mpv.conf"]]
[tasks.neofetch]
    cmds = [["@install", "neofetch"]]
    links = [[".config/neofetch"]]
[tasks.composer]
    cmds = [["@install", "php"],
# Install composer here TOADD
    links = [[".config/composer/composer.json"]]
[tasks.vlc]
    cmds = [["@install", "vlc"], ["/usr/lib/vlc/vlc-cache-gen", "-f", "/usr/lib/vlc/plugins"]]
[tasks.i3]
    cmds = [["@install", "lemonbar-xft-git"]]
    links = [[".i3"]]
[tasks.ranger]
    cmds = [["@install", "ranger"]]
    links = [[".config/ranger/rc.conf"],
        [".config/ranger/rifle.conf"],
        [".config/ranger/scope.sh"]]
[tasks.dunst]
    cmds = [["@install", "dunst"]]
    links = [[".config/dunst/dunstrc"]]
[tasks.compton]
    cmds = [["@install", "compton"]]
    links = [[".config/compton.conf"]]
[tasks.teiler]
    cmds = [["@install", "teiler"]]
    links = [[".config/teiler/config"]]
[tasks.fonts]
    links = [[".local/share/fonts"]]
[tasks.default]
    deps = ["common", "vim", "fish"]
[tasks.default__arch]
    deps = ["desktop", "fonts", "audio", "i3", "redshift", "ranger", "dunst", "compton", "teiler", "browser", "composer", "neofetch", "mpv"]
