#
# macros
#
[macros.clone]
	prefix = ["git", "clone"]
[macros.install]
	prefix = ["sudo", "pacman", "-S", "--noconfirm"]
[macros.enable]
	prefix = ["sudo", "systemctl", "enable"]
[macros.aur]
	prefix = ["yaourt", "-S", "--noconfirm"]
#
# system
#
[tasks.fish]
	rejects = [["which", "fish"]]
	cmds = [["@install", "fish"], ["chsh", "-s", "$(which fish)"]]
	links = [[".config/fish/config.fish"]]
[tasks.libreoffice]
	cmds = [["@install", "libreoffice-fresh"]]
[tasks.vim]
	cmds = [["@install", "neovim"]]
[tasks.urxvt]
	cmds = [["@install", "urxvt"]]
[tasks.audio]
	cmds = [["@install", "pulseaudio", "alsa-utils", "pavucontrol"]]
[tasks.zip]
	cmds = [["@install", "unzip"]]
[tasks.common]
	cmds = [["@install", "gimp", "keepassx2", "xf86-input-synaptics", "rofi", "dunst", "mps-youtube", "kdenlive"]]
	links = [[".Xresources"]]
[tasks.redshift]
	cmds = [["@install", "redshift"]]
	links = [[".config/redshift.conf"],
		[".config/redshift/hooks/brightness.sh"]]
[tasks.fonts]
	links = [[".fonts"]]
[tasks.userpackage]
	cmds = [["@aur", "slack-desktop"],
		["@aur", "telegram-desktop"],
		["@aur", "vivaldi"],
		["@aur", "trackma-git"]]
[tasks.vlc]
	cmds = [["@install", "vlc"], ["/usr/lib/vlc/vlc-cache-gen", "-f", "/usr/lib/vlc/plugins"]]
[tasks.i3]
	cmds = [["@install", "i3-gaps"],
		["@aur", "lemonbar-xft-git"],
		["@aur", "i3blocks"]]
	links = [[".config/i3/config"],
		[".script"]]
[tasks.i3__dekstop]
	deps = ["i3"]
	links = [["$HM_SRC/desktop/.i3blocks.conf", ".i3blocks.conf"]]
[tasks.screenlayout]
[tasks.screenlayout__desktop]
	links = [["$HM_SRC/desktop/bin/screenlayout", "$HM_DEST/bin/screenlayout"]]
[tasks.screencofig]
[tasks.xscreensaver]
	cmds = [["@install", "xscreensaver"]]
	#links = [[".xscreensaver"]]
[tasks.powerline]
	cmds = [["@install", "powerline"]]
[tasks.default]
	deps = ["common", "vim", "fish", "libreoffice", "fonts", "audio", "xscreensaver", "powerline", "i3", "userpackage", "redshift"]
