#!/bin/sh
lock() {
    i3lock
}

case "$1" in
    lock)
        i3lock
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        pm-suspend && i3lock
        ;;
    hibernate)
        systemctl hibernate && i3lock-fancy
        ;;
    reboot)
        openrc-shutdown -r
        ;;
    shutdown)
        sudo openrc-shudtdown -p
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
