#!/bin/sh
lock() {
    i3lock
}

case "$1" in
    lock)
        i3lock
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        i3lock && sudo pm-suspend
        ;;
    hibernate)
        i3lock && sudo pm-hibernate
        ;;
    reboot)
        sudo openrc-shutdown -r
        ;;
    shutdown)
        sudo openrc-shutdown -p
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
