#!/bin/sh
lock() {
    i3lock
}

case "$1" in
    lock)
        i3lock-fancy
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        systemctl suspend && i3lock-fancy
        ;;
    hibernate)
        systemctl hibernate && i3lock-fancy
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
