#!/usr/bin/sh

DESCRIPTION="Critical battery level.\nPut the charger on."
POWER_ADAPTER="/sys/class/power_supply/ADP1/online"
BATTERY="/sys/class/power_supply/BAT0/capacity"
CRITICAL_LEVEL=60

BATTERY_LEVEL=$(cat $BATTERY)
CHARGING=$(cat $POWER_ADAPTER)

SUMMARY="Low battery ($BATTERY_LEVEL%)"

if [ "$BATTERY_LEVEL" -le "$CRITICAL_LEVEL" ] && [ "$CHARGING" = 0 ]; then
    notify-send -u critical -t 5000 "$SUMMARY" "$DESCRIPTION"
fi
