#!/usr/bin/sh

# Get fields from mpc, split by tabs.
IFS=$'\t' read FILENAME ARTIST TITLE ALBUM \
  <<< "$(mpc --format="%file%\t%artist%\t%title%\t%album%" -h '127.0.0.1')"

if [ -z "$TITLE" ];
then
    FILENAME=$(echo $FILENAME | cut -f 1 -d '.')
    ARTIST=$(echo $FILENAME | cut -f 1 -d '-')
    TITLE=$(echo $FILENAME | cut -f 2 -d '-')
fi

if [ ! -z "$ARTIST" ];
then
    ARTIST="From: $ARTIST"
fi

if [ ! -z "$ALBUM" ];
then
    ALBUM="Album: $ALBUM"
fi

notify-send --app-name=ncmpcpp \
  --icon=audio-x-generic "$TITLE" "$ARTIST\n$ALBUM"
