#!/bin/sh

export PATH=${HOME}/.local/bin:/usr/local/benice:/usr/bin

export EDITOR=kak
export VISUAL=kak

export GPG_TTY=$(tty)

# Load settings for XDG home directories
. ~/.config/xdg_dirs

. /etc/os-release

. ${XDG_CONFIG_HOME}/profile.wayland

export GRADLE_USER_HOME=${XDG_CONFIG_HOME}/gradle

# add rustup
source "$HOME/.cargo/env"
