#!/bin/sh

export PATH=${HOME}/.local/bin:/usr/local/benice:/usr/bin

export EDITOR=hx
export VISUAL=hx

export GPG_TTY=$(tty)

# Load settings for XDG home directories
. ~/.config/xdg_dirs

. /etc/os-release

. ${XDG_CONFIG_HOME}/profile.wayland

export GRADLE_USER_HOME=${XDG_CONFIG_HOME}/gradle

# add rustup
source "$HOME/.cargo/env"

export NNN_PLUG='p:preview'
export NNN_FIFO=/tmp/nnn.fifo
