# Don't print a new line at the start of the prompt
add_newline = false

# Replace the "❯" symbol in the prompt with "➜"
[character]
success_symbol = "[➜](green)"
error_symbol = "[➜](red)"

[username]
show_always = true

[hostname]
ssh_only = true

[status]
format = "[$symbol$status]($style) "
symbol = ""
disabled = false
