#!/usr/bin/bash

# Set vi mode
#set -o vi
#set interactive

# shopt -q login_shell && \
    . ${HOME}/.config/profile

. ${XDG_CONFIG_HOME}/oil/env

. ${XDG_CONFIG_HOME}/oil/aliases
. ${XDG_CONFIG_HOME}/oil/functions
. ${XDG_CONFIG_HOME}/oil/keys
. ${XDG_CONFIG_HOME}/oil/prompt
. ${XDG_CONFIG_HOME}/oil/plugins
. ${XDG_CONFIG_HOME}/LESS_TERMCAP
