[semantic_scopes]
# Map textmate scopes to kakoune faces for semantic highlighting
# the underscores are translated to dots, and indicate nesting.
# That is, if variable_other_field is omitted, it will try the face for
# variable_other and then variable
#
# To see a list of available scopes in the debug buffer, run lsp-semantic-available-scopes
variable = "variable"
entity_name_function = "function"
entity_name_type = "type"
variable_other_enummember = "variable"
entity_name_namespace = "module"

[language.c_cpp]
filetypes = ["c", "cpp"]
roots = [".clangd", "build"]
command = "clangd"
#offset_encoding = "utf-8"
args = ["--clang-tidy", "--pretty", "--offset-encoding=utf-8", "--background-index", "--all-scopes-completion", "--suggest-missing-includes", "--header-insertion=iwyu", "-j=9", "--completion-style=detailed", "--pch-storage=memory"]

[language.py]
filetypes = ["python"]
roots = ["requirements.txt", "setup.py", ".git", ".hg"]
offset_encoding = "utf-8"
command = "pyls"

[language.javascript]
filetypes = ["javascript"]
roots = [".flowconfig"]
command = "flow"
args = ["lsp"]

[language.zig]
filetypes = ["zig"]
roots = ["build.zig"]
command = "zls"

[language.elixir]
filetypes = ["elixir"]
roots = ["mix.exs"]
command = "elixir-ls"

[language.vala]
filetypes = ["vala"]
roots = ["meson.build"]
command = "org.gnome.gvls.stdio.Server"
