theme = "monokai_pro"

[editor]
line-number = "relative"
mouse = false
#idle-timeout = 0
#completion-trigger-len = 1
rulers = [100]

[editor.whitespace]
render = "all"

[editor.whitespace.characters]
space = "·"
tab = "→"
newline = "¬"

[keys.normal]
q = "move_prev_word_start"
Q = "move_prev_long_word_start"

[keys.select]
q = "move_prev_word_start"
Q = "move_prev_long_word_start"
